# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ..base import StringInterpolate


def test_StringInterpolate_inputs():
    input_map = dict(
        input_string=dict(
            mandatory=True,
        ),
    )
    inputs = StringInterpolate.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value


def test_StringInterpolate_outputs():
    output_map = dict(
        output_string=dict(),
    )
    outputs = StringInterpolate.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
